### ISSUE TITLE
Called setPositions() on a Context with the wrong number of positions

### ISSUE THREAD

**Issue by hanboy315** [choderalab/espaloma#193]
Reopen issue (wrong respository posted)...

Hi, I'm trying to build a small molecule cell and run espaloma-0.3.0 on them. I keep getting a position error stating, 
```
/home/hy2120/miniconda/envs/openff/lib/python3.10/site-packages/dgl/backend/pytorch/tensor.py:352: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  assert input.numel() == input.storage().size(), "Cannot convert view " \
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
  File "/home/hy2120/miniconda/envs/openff/lib/python3.10/site-packages/openmm/openmm.py", line 3479, in setPositions
    return _openmm.Context_setPositions(self, positions)
openmm.OpenMMException: Called setPositions() on a Context with the wrong number of positions
```

**Comment by hanboy315** [comment]
I've allowed the topology to be the same as my 'molecule'. If there is only one molecule it works (sure) but if it's >1 the problem remains. My .py now looks something like this. My workflow begins with packmol'ing two small molecules and that is the Y6_2_out.mol/.gro
```
import os
import torch
import espaloma as esp

from openff.toolkit.utils import get_data_file_path

from openmm.app import *
from openmm import *
from openmm.unit import *
from sys import stdout

from openff.toolkit.topology import Topology, Molecule

from openff.toolkit.utils.toolkits import RDKitToolkitWrapper

# read in molecules to molecular dynamics
startpositions = GromacsGroFile('/home/hy2120/single-y6/espaloma_on_single_y6/dimer/Y6_2_out.gro').positions
mol_filepath = get_data_file_path('/home/hy2120/single-y6/espaloma_on_single_y6/dimer/Y6_2_out.mol') 

# See here: https://docs.openforcefield.org/projects/toolkit/en/stable/users/molecule_cookbook.html#from-small-molecule-pdb-file
molecule = Molecule.from_file(mol_filepath,"mol", toolkit_registry=RDKitToolkitWrapper())
molecule_graph = esp.Graph(molecule)

# load Espaloma
espaloma_model = esp.get_model("latest")
espaloma_model(molecule_graph.heterograph)
omm_system = esp.graphs.deploy.openmm_system_from_graph(molecule_graph)
# OK; we have our force-field now

# ensure we have correct Topology objects (OpenFF and OpenMM, jeese)
off_topology = Topology.from_molecules(molecule)
omm_topology = off_topology.to_openmm()

# Molecular dynamics setup
integrator = LangevinMiddleIntegrator(300 * kelvin, 1 / picosecond, 0.001 * picoseconds)
simulation = Simulation(omm_topology, omm_system, integrator)
simulation.context.setPositions(startpositions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('/home/hy2120/y6/output.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
        potentialEnergy=True, temperature=True))
simulation.step(10000)
```

**Comment by mikemhenry** [comment]
Dupe of https://github.com/choderalab/espaloma/issues/194 (I transferred the old one and @hanboy315 opened this one in the correct location, but the old issue had more conversation that I didn't want to loose while we work out the issue)
