### ISSUE TITLE
Called setPositions() on a Context with the wrong number of positions

### ISSUE THREAD

**Issue by hanboy315** [choderalab/espaloma#194]
Trying to use the pre-trained espaloma-0.3.0 on my supercell, and came across this vague error that I can't seem to get the origin of?

```
/home/hy2120/miniconda/envs/openff/lib/python3.10/site-packages/dgl/heterograph.py:72: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning('Recommend creating graphs by `dgl.graph(data)'
/home/hy2120/miniconda/envs/openff/lib/python3.10/site-packages/dgl/backend/pytorch/tensor.py:352: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  assert input.numel() == input.storage().size(), "Cannot convert view " \
Traceback (most recent call last):
  File "<stdin>", line 25, in <module>
  File "/home/hy2120/miniconda/envs/openff/lib/python3.10/site-packages/openmm/openmm.py", line 3479, in setPositions
    return _openmm.Context_setPositions(self, positions)
openmm.OpenMMException: Called setPositions() on a Context with the wrong number of positions
```

**Comment by mikemhenry** [comment]
@ijpulidos @yuanqing-wang any ideas here?

**Comment by jarvist** [comment]
We worked around this by borrowing approaches in #192 and using the `EspalomaTemplateGenerator`which we then put in an `openff.Forcefield` object in order to use the `openmm.app.Modeller`. This approach seemed to be happily start a multi-molecule input file in Espaloma, and though I have not checked carefully the Forcefield is correct, the dynamics looked sensible. 
I'm always a bit lost debugging Python and end up trying different instantiated objects until something works. 

https://github.com/Frost-group/ConjugatedEspaloma/commit/61e52802f27e286931fe2f099d25011e82a8ee0b

**Comment by mikemhenry** [comment]
@ijpulidos we should update our docs to include a little example like this
