### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED at "esp.get_model("latest")" step

### ISSUE THREAD

**Issue by beavenah** [choderalab/espaloma#215]
Hi all,

I'm using a MacBook M3 and using mandatory Zscaler for security. I was able to install espaloma on my laptop, but when I get to the "esp.get_model("latest")" step, I get:

```
>>> import espaloma as esp
>>> from openff.toolkit.topology import Molecule
>>> molecule = Molecule.from_smiles("CN1C=NC2=C1C(=O)N(C(=O)N2C)C")
>>> molecule_graph = esp.Graph(molecule)
/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
>>> espaloma_model = esp.get_model("latest")
Downloading: "https://github.com/choderalab/espaloma/releases/latest/download/espaloma-latest.pt" to /Users/abeaven/.cache/torch/hub/checkpoints/espaloma-latest.pt
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/site-packages/espaloma/utils/model_fetch.py", line 116, in get_model
    model = torch.utils.model_zoo.load_url(url, map_location="cpu")
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/site-packages/torch/hub.py", line 746, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/espaloma/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:1007)>
```

It was recommended that I try `pip3 install pip_system_certs --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host github.com` in my conda base and espaloma conda, but I get the same SSL errors. Does anyone have a recommendation of what to do? Can I download the `espaloma-latest.pt` myself and use it instead of trying to pull it from GitHub in the python script? If so, how would I change the script?

Thanks again!

**Comment by ijpulidos** [comment]
@beavenah It seems like your network is doing something strange when trying to download the model.

The good news is that you can indeed download the model yourself and load it from a path using `torch`, it would be something like the following:

```python
import torch
espaloma_model = torch.load("/path/to/espaloma-latest.pt")
espaloma_model.eval()
```

I hope this works!

**Comment by mikemhenry** [comment]
@mattwthompson might have the answer

**Comment by mattwthompson** [comment]
Hey @beavenah,

It looks like you're on the right track, but
* An `Interchange` object, once constructed, contains all of the information needed to write out GROMACS (or OpenMM, etc.) files, so all that's needed is pointing it to a file path. There's also `.to_gromacs("filename")` which just calls out to the topology and coordinate file writers in one go.
  * https://docs.openforcefield.org/projects/interchange/en/stable/using/output.html#gromacs
  * https://docs.openforcefield.org/projects/interchange/en/stable/_autosummary/openff.interchange.Interchange.html?highlight=to_gromacs#openff.interchange.Interchange.to_gromacs
* There are some sharp edges with `Interchange.from_openmm`. I don't recall if or how recently people have tried to use Espaloma with it
  * https://docs.openforcefield.org/projects/interchange/en/stable/_autosummary/openff.interchange.Interchange.html#openff.interchange.Interchange.from_openmm
* If you run into future issues, could you open a new "Discussion" within the OpenFF org? It seems like your original Espaloma-specific issue is resolved and we'll be able to help you out with Interchange questions over there
  * https://github.com/orgs/openforcefield/discussions

**Comment by beavenah** [comment]
Thank you, @mikemhenry and @mattwthompson! It appears that I have a functional script based on other GitHub discussions I've seen... But, I'll still plan to open a new discussion at the openFF GitHub. I'll just check a few more things on my end first.
